### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by GABSEOKKIM** [netarc/serial-modem#1]
Arduino : 1.6.0
Board : Arduino UNO

In file included from ArduinoUno.ino:1:0:
/Users/ScottKim/Documents/WorkSpaceForArduino/libraries/SerialModem/SerialModem.h:94:35: error: variable 'Modem::RESPONSE_OK' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
   extern char PROGMEM RESPONSE_OK[];
                                   ^
/Users/ScottKim/Documents/WorkSpaceForArduino/libraries/SerialModem/SerialModem.h:95:38: error: variable 'Modem::RESPONSE_ERROR' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
   extern char PROGMEM RESPONSE_ERROR[];
                                      ^
Error compiling.

**Comment by smassmann62** [comment]
I also got this error, went into the file and made the variables const, and then I got these errors:

C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp: In constructor 'Modem::PMemString::PMemString(const Modem::__PMemStringRef*)':
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:16:64: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
       _buffer = (char *)malloc(strlen_P(reinterpret_cast<const prog_char *>(ptr)) + 1);
                                                                ^
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:16:64: error: expected '>' before 'prog_char'
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:16:64: error: expected '(' before 'prog_char'
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:16:64: error: 'prog_char' was not declared in this scope
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:16:75: error: expected primary-expression before '>' token
       _buffer = (char *)malloc(strlen_P(reinterpret_cast<const prog_char *>(ptr)) + 1);
                                                                           ^
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:17:48: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
       strcpy_P(_buffer, reinterpret_cast<const prog_char *>(ptr));
                                                ^
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:17:48: error: expected '>' before 'prog_char'
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:17:48: error: expected '(' before 'prog_char'
C:\Users\quspm1\Documents\Arduino\libraries\SerialModem\util.cpp:17:59: error: expected primary-expression before '>' token
       strcpy_P(_buffer, reinterpret_cast<const prog_char *>(ptr));
                                                           ^
Error compiling.

**Comment by netarc** [comment]
@GABSEOKKIM @smassmann62 thanks for finding this, I recently encountered the above *\* must be const in order to be put into read-only section*\* with the new IDE and have recently pushed some changes to address that.
